
[functions.spotify-auth]
enabled = true
verify_jwt = true
import_map = "./functions/spotify-auth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-auth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-auth/*.html" ]

[functions.spotify-callback]
enabled = true
verify_jwt = false
import_map = "./functions/spotify-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/spotify-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/spotify-callback/*.html" ]

[functions.fetch-spotify-analytics]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-spotify-analytics/deno.json"
entrypoint = "./functions/fetch-spotify-analytics/index.ts"
