ALTER TABLE "public"."projects"
ADD COLUMN IF NOT EXISTS "producers" TEXT[],
ADD COLUMN IF NOT EXISTS "composers" TEXT[],
ADD COLUMN IF NOT EXISTS "credits" TEXT,
ADD COLUMN IF NOT EXISTS "lyrics" TEXT,
ADD COLUMN IF NOT EXISTS "splits" JSONB;
