ALTER TABLE public.artists
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS bank_info JSONB,
ADD COLUMN IF NOT EXISTS management_entity TEXT,
ADD COLUMN IF NOT EXISTS ipi TEXT;